# Generated by Django 5.1.1 on 2024-10-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Staff', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
