# Generated by Django 5.1.1 on 2024-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
