# Generated by Django 5.1.1 on 2024-10-20 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leave_leaverequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('PTO', 'Paid Time Off'), ('SICK', 'Sick Leave'), ('VACATION', 'Vacation')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='requested_days',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.CharField(default='No reason provided', max_length=255),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves', models.IntegerField(default=20)),
                ('used_leaves', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
